dist: trusty
sudo: required
language: java
jdk:
  - openjdk7
python:
  - "2.7"
install:
  - curl -s http://www.eu.apache.org/dist/hadoop/common/hadoop-2.6.5/hadoop-2.6.5.tar.gz | tar -xz
before_script:
  - export HADOOP_HOME=`readlink -f hadoop-2.6.5`
  - export LDBC_SNB_DATAGEN_HOME=`pwd`
  - export HADOOP_CLIENT_OPTS="-Xmx2G"
script:
  - mvn test
  - ls ./test_data
  - ls ./test_data/social_network
  - ls ./test_data/substitution_parameters
  - head -n 15 ./test_data/substitution_parameters/query_2_param.txt
  - cat ./parameters_interactive.log
  - cat ./parameters_bi.log
notifications:
  slack: ldbcouncil:OrBanrJ7l0EHQbj8T5YdJYhd
  email: false
  on_success: change
  on_failure: always
