dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
python:
  - "2.7"
script:
  - mvn test
  - wc -l ./test_data/social_network/*
notifications:
  slack: ldbcouncil:OrBanrJ7l0EHQbj8T5YdJYhd
  email: false
  on_success: change
  on_failure: always
